# Generated by Django 6.0.7 on 2026-07-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_at_user_role_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Unknown User', max_length=255),
            preserve_default=False,
        ),
    ]
