# Generated by Django 6.0.7 on 2026-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
